apiVersion: v1
kind: Service
metadata:
  namespace: elastic
  name: elasticsearch-svc
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: http-port
    - port: 9300
      name: transport-port
      
