apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic
  name: filebeat-configmap
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          enabled: true
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          enabled: true
          var.paths: ["/var/log/nginx/access.log*"]
    output.elasticsearch:
      hosts: ["localhosts:9200"]
