apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: elastic
  name: nginx-filebeat-sidecar
  labels:
    app: nginx-filebeat-sidecar
spec:
  replicas: 1
  selector:
    matchLabels: nginx-filebeat-sidecar
      app:
  template:
    metadata:
      name: nginx-filebeat-sidecar
      labels:
        app: nginx-filebeat-sidecar
    spce:
      containers:
        - name: nginx
          image: nginx
          ports: 
            - containerPort: 80
          volumeMounts:
            - name: nginx-logs
              mountPath: var/log/nginx/
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
    volumes:
      - name: nginx-logs
      - name: filebeat-config
        configMap:
          name: filebeat-config
          items:
            - key: filebeat.yml
              path: filebeat.yml
